provider: external
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
env:
  EXTERNAL_TOKEN: ${{ secrets.EXTERNAL_TOKEN }}
pulumiConvert: 1
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
