provider: external
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
env:
    EXTERNAL_TOKEN: ${{ secrets.EXTERNAL_TOKEN }} # TODO(https://github.com/pulumi/pulumi-external/issues/14): This is not set.
pulumiConvert: 1
