// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.External
{
    public static class GetExternal
    {
        /// <summary>
        /// The `external.getExternal` data source allows an external program implementing a specific protocol (defined below) to act as a data source, exposing arbitrary data for use elsewhere in the Terraform configuration.
        /// 
        /// **Warning** This mechanism is provided as an "escape hatch" for exceptional situations where a first-class Terraform provider is not more appropriate. Its capabilities are limited in comparison to a true data source, and implementing a data source via an external program is likely to hurt the portability of your Terraform configuration by creating dependencies on external programs and libraries that may not be available (or may need to be used differently) on different operating systems.
        /// 
        /// **Warning** Terraform Enterprise does not guarantee availability of any particular language runtimes or external programs beyond standard shell utilities, so it is not recommended to use this data source within configurations that are applied within Terraform Enterprise.
        /// 
        /// ## Processing JSON in shell scripts
        /// 
        /// Since the external data source protocol uses JSON, it is recommended to use
        /// the utility [`Jq`](https://stedolan.github.io/jq/) to translate to and from
        /// JSON in a robust way when implementing a data source in a shell scripting
        /// language.
        /// 
        /// The following example shows some input/output boilerplate code for a
        /// data source implemented in bash:
        /// 
        /// ```shell
        /// #!/bin/bash
        /// 
        /// # Exit if any of the intermediate steps fail
        /// set -e
        /// 
        /// # Extract "foo" and "baz" arguments from the input into
        /// # FOO and BAZ shell variables.
        /// # jq will ensure that the values are properly quoted
        /// # and escaped for consumption by the shell.
        /// eval "$(jq -r '@sh "FOO=\(.foo) BAZ=\(.baz)"')"
        /// 
        /// # Placeholder for whatever data-fetching logic your script implements
        /// FOOBAZ="$FOO $BAZ"
        /// 
        /// # Safely produce a JSON object containing the result value.
        /// # jq will ensure that the value is properly quoted
        /// # and escaped to produce a valid JSON string.
        /// jq -n --arg foobaz "$FOOBAZ" '{"foobaz":$foobaz}'
        /// ```
        /// </summary>
        public static Task<GetExternalResult> InvokeAsync(GetExternalArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetExternalResult>("external:index/getExternal:getExternal", args ?? new GetExternalArgs(), options.WithDefaults());

        /// <summary>
        /// The `external.getExternal` data source allows an external program implementing a specific protocol (defined below) to act as a data source, exposing arbitrary data for use elsewhere in the Terraform configuration.
        /// 
        /// **Warning** This mechanism is provided as an "escape hatch" for exceptional situations where a first-class Terraform provider is not more appropriate. Its capabilities are limited in comparison to a true data source, and implementing a data source via an external program is likely to hurt the portability of your Terraform configuration by creating dependencies on external programs and libraries that may not be available (or may need to be used differently) on different operating systems.
        /// 
        /// **Warning** Terraform Enterprise does not guarantee availability of any particular language runtimes or external programs beyond standard shell utilities, so it is not recommended to use this data source within configurations that are applied within Terraform Enterprise.
        /// 
        /// ## Processing JSON in shell scripts
        /// 
        /// Since the external data source protocol uses JSON, it is recommended to use
        /// the utility [`Jq`](https://stedolan.github.io/jq/) to translate to and from
        /// JSON in a robust way when implementing a data source in a shell scripting
        /// language.
        /// 
        /// The following example shows some input/output boilerplate code for a
        /// data source implemented in bash:
        /// 
        /// ```shell
        /// #!/bin/bash
        /// 
        /// # Exit if any of the intermediate steps fail
        /// set -e
        /// 
        /// # Extract "foo" and "baz" arguments from the input into
        /// # FOO and BAZ shell variables.
        /// # jq will ensure that the values are properly quoted
        /// # and escaped for consumption by the shell.
        /// eval "$(jq -r '@sh "FOO=\(.foo) BAZ=\(.baz)"')"
        /// 
        /// # Placeholder for whatever data-fetching logic your script implements
        /// FOOBAZ="$FOO $BAZ"
        /// 
        /// # Safely produce a JSON object containing the result value.
        /// # jq will ensure that the value is properly quoted
        /// # and escaped to produce a valid JSON string.
        /// jq -n --arg foobaz "$FOOBAZ" '{"foobaz":$foobaz}'
        /// ```
        /// </summary>
        public static Output<GetExternalResult> Invoke(GetExternalInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetExternalResult>("external:index/getExternal:getExternal", args ?? new GetExternalInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The `external.getExternal` data source allows an external program implementing a specific protocol (defined below) to act as a data source, exposing arbitrary data for use elsewhere in the Terraform configuration.
        /// 
        /// **Warning** This mechanism is provided as an "escape hatch" for exceptional situations where a first-class Terraform provider is not more appropriate. Its capabilities are limited in comparison to a true data source, and implementing a data source via an external program is likely to hurt the portability of your Terraform configuration by creating dependencies on external programs and libraries that may not be available (or may need to be used differently) on different operating systems.
        /// 
        /// **Warning** Terraform Enterprise does not guarantee availability of any particular language runtimes or external programs beyond standard shell utilities, so it is not recommended to use this data source within configurations that are applied within Terraform Enterprise.
        /// 
        /// ## Processing JSON in shell scripts
        /// 
        /// Since the external data source protocol uses JSON, it is recommended to use
        /// the utility [`Jq`](https://stedolan.github.io/jq/) to translate to and from
        /// JSON in a robust way when implementing a data source in a shell scripting
        /// language.
        /// 
        /// The following example shows some input/output boilerplate code for a
        /// data source implemented in bash:
        /// 
        /// ```shell
        /// #!/bin/bash
        /// 
        /// # Exit if any of the intermediate steps fail
        /// set -e
        /// 
        /// # Extract "foo" and "baz" arguments from the input into
        /// # FOO and BAZ shell variables.
        /// # jq will ensure that the values are properly quoted
        /// # and escaped for consumption by the shell.
        /// eval "$(jq -r '@sh "FOO=\(.foo) BAZ=\(.baz)"')"
        /// 
        /// # Placeholder for whatever data-fetching logic your script implements
        /// FOOBAZ="$FOO $BAZ"
        /// 
        /// # Safely produce a JSON object containing the result value.
        /// # jq will ensure that the value is properly quoted
        /// # and escaped to produce a valid JSON string.
        /// jq -n --arg foobaz "$FOOBAZ" '{"foobaz":$foobaz}'
        /// ```
        /// </summary>
        public static Output<GetExternalResult> Invoke(GetExternalInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetExternalResult>("external:index/getExternal:getExternal", args ?? new GetExternalInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetExternalArgs : global::Pulumi.InvokeArgs
    {
        [Input("programs", required: true)]
        private List<string>? _programs;

        /// <summary>
        /// A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
        /// </summary>
        public List<string> Programs
        {
            get => _programs ?? (_programs = new List<string>());
            set => _programs = value;
        }

        [Input("query")]
        private Dictionary<string, string>? _query;

        /// <summary>
        /// A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
        /// </summary>
        public Dictionary<string, string> Query
        {
            get => _query ?? (_query = new Dictionary<string, string>());
            set => _query = value;
        }

        /// <summary>
        /// Working directory of the program. If not supplied, the program will run in the current directory.
        /// </summary>
        [Input("workingDir")]
        public string? WorkingDir { get; set; }

        public GetExternalArgs()
        {
        }
        public static new GetExternalArgs Empty => new GetExternalArgs();
    }

    public sealed class GetExternalInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("programs", required: true)]
        private InputList<string>? _programs;

        /// <summary>
        /// A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
        /// </summary>
        public InputList<string> Programs
        {
            get => _programs ?? (_programs = new InputList<string>());
            set => _programs = value;
        }

        [Input("query")]
        private InputMap<string>? _query;

        /// <summary>
        /// A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
        /// </summary>
        public InputMap<string> Query
        {
            get => _query ?? (_query = new InputMap<string>());
            set => _query = value;
        }

        /// <summary>
        /// Working directory of the program. If not supplied, the program will run in the current directory.
        /// </summary>
        [Input("workingDir")]
        public Input<string>? WorkingDir { get; set; }

        public GetExternalInvokeArgs()
        {
        }
        public static new GetExternalInvokeArgs Empty => new GetExternalInvokeArgs();
    }


    [OutputType]
    public sealed class GetExternalResult
    {
        /// <summary>
        /// The id of the data source. This will always be set to `-`
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
        /// </summary>
        public readonly ImmutableArray<string> Programs;
        /// <summary>
        /// A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Query;
        /// <summary>
        /// A map of string values returned from the external program.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Result;
        /// <summary>
        /// Working directory of the program. If not supplied, the program will run in the current directory.
        /// </summary>
        public readonly string? WorkingDir;

        [OutputConstructor]
        private GetExternalResult(
            string id,

            ImmutableArray<string> programs,

            ImmutableDictionary<string, string>? query,

            ImmutableDictionary<string, string> result,

            string? workingDir)
        {
            Id = id;
            Programs = programs;
            Query = query;
            Result = result;
            WorkingDir = workingDir;
        }
    }
}
