// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getExternal(args: GetExternalArgs, opts?: pulumi.InvokeOptions): Promise<GetExternalResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("external:index/getExternal:getExternal", {
        "programs": args.programs,
        "query": args.query,
        "workingDir": args.workingDir,
    }, opts);
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalArgs {
    programs: string[];
    query?: {[key: string]: string};
    workingDir?: string;
}

/**
 * A collection of values returned by getExternal.
 */
export interface GetExternalResult {
    readonly id: string;
    readonly programs: string[];
    readonly query?: {[key: string]: string};
    readonly result: {[key: string]: string};
    readonly workingDir?: string;
}
export function getExternalOutput(args: GetExternalOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetExternalResult> {
    return pulumi.output(args).apply((a: any) => getExternal(a, opts))
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalOutputArgs {
    programs: pulumi.Input<pulumi.Input<string>[]>;
    query?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    workingDir?: pulumi.Input<string>;
}
