// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The `external.getExternal` data source allows an external program implementing a specific protocol (defined below) to act as a data source, exposing arbitrary data for use elsewhere in the Terraform configuration.
 *
 * **Warning** This mechanism is provided as an "escape hatch" for exceptional situations where a first-class Terraform provider is not more appropriate. Its capabilities are limited in comparison to a true data source, and implementing a data source via an external program is likely to hurt the portability of your Terraform configuration by creating dependencies on external programs and libraries that may not be available (or may need to be used differently) on different operating systems.
 *
 * **Warning** Terraform Enterprise does not guarantee availability of any particular language runtimes or external programs beyond standard shell utilities, so it is not recommended to use this data source within configurations that are applied within Terraform Enterprise.
 *
 * ## Processing JSON in shell scripts
 *
 * Since the external data source protocol uses JSON, it is recommended to use
 * the utility [`jq`](https://stedolan.github.io/jq/) to translate to and from
 * JSON in a robust way when implementing a data source in a shell scripting
 * language.
 *
 * The following example shows some input/output boilerplate code for a
 * data source implemented in bash:
 */
export function getExternal(args: GetExternalArgs, opts?: pulumi.InvokeOptions): Promise<GetExternalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("external:index/getExternal:getExternal", {
        "programs": args.programs,
        "query": args.query,
        "workingDir": args.workingDir,
    }, opts);
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalArgs {
    /**
     * A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
     */
    programs: string[];
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    query?: {[key: string]: string};
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    workingDir?: string;
}

/**
 * A collection of values returned by getExternal.
 */
export interface GetExternalResult {
    /**
     * The id of the data source. This will always be set to `-`
     */
    readonly id: string;
    /**
     * A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
     */
    readonly programs: string[];
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    readonly query?: {[key: string]: string};
    /**
     * A map of string values returned from the external program.
     */
    readonly result: {[key: string]: string};
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    readonly workingDir?: string;
}
/**
 * The `external.getExternal` data source allows an external program implementing a specific protocol (defined below) to act as a data source, exposing arbitrary data for use elsewhere in the Terraform configuration.
 *
 * **Warning** This mechanism is provided as an "escape hatch" for exceptional situations where a first-class Terraform provider is not more appropriate. Its capabilities are limited in comparison to a true data source, and implementing a data source via an external program is likely to hurt the portability of your Terraform configuration by creating dependencies on external programs and libraries that may not be available (or may need to be used differently) on different operating systems.
 *
 * **Warning** Terraform Enterprise does not guarantee availability of any particular language runtimes or external programs beyond standard shell utilities, so it is not recommended to use this data source within configurations that are applied within Terraform Enterprise.
 *
 * ## Processing JSON in shell scripts
 *
 * Since the external data source protocol uses JSON, it is recommended to use
 * the utility [`jq`](https://stedolan.github.io/jq/) to translate to and from
 * JSON in a robust way when implementing a data source in a shell scripting
 * language.
 *
 * The following example shows some input/output boilerplate code for a
 * data source implemented in bash:
 */
export function getExternalOutput(args: GetExternalOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetExternalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("external:index/getExternal:getExternal", {
        "programs": args.programs,
        "query": args.query,
        "workingDir": args.workingDir,
    }, opts);
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalOutputArgs {
    /**
     * A list of strings, whose first element is the program to run and whose subsequent elements are optional command line arguments to the program. Terraform does not execute the program through a shell, so it is not necessary to escape shell metacharacters nor add quotes around arguments containing spaces.
     */
    programs: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    query?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    workingDir?: pulumi.Input<string>;
}
