// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getExternal(args: GetExternalArgs, opts?: pulumi.InvokeOptions): Promise<GetExternalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("external:index/getExternal:getExternal", {
        "programs": args.programs,
        "query": args.query,
        "workingDir": args.workingDir,
    }, opts);
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalArgs {
    programs: string[];
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    query?: {[key: string]: string};
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    workingDir?: string;
}

/**
 * A collection of values returned by getExternal.
 */
export interface GetExternalResult {
    /**
     * The id of the data source. This will always be set to `-`
     */
    readonly id: string;
    readonly programs: string[];
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    readonly query?: {[key: string]: string};
    /**
     * A map of string values returned from the external program.
     */
    readonly result: {[key: string]: string};
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    readonly workingDir?: string;
}
export function getExternalOutput(args: GetExternalOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetExternalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("external:index/getExternal:getExternal", {
        "programs": args.programs,
        "query": args.query,
        "workingDir": args.workingDir,
    }, opts);
}

/**
 * A collection of arguments for invoking getExternal.
 */
export interface GetExternalOutputArgs {
    programs: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A map of string values to pass to the external program as the query arguments. If not supplied, the program will receive an empty object as its input.
     */
    query?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Working directory of the program. If not supplied, the program will run in the current directory.
     */
    workingDir?: pulumi.Input<string>;
}
